In [1]:
import numpy as np
import NNN
import EEE
import importlib

Opening data file in RRR, 23
Opening data file in RRR, 23
in NNN, ABC = 9.941898256564475
Opening data file in RRR, 23


In [2]:
index = np.random.randint(100)
np.savez("blah_data", i = index, A = index + 0.1*np.random.randn(5), B = -index + 0.1 * np.random.randn(8), C = np.sqrt(index))
print("Data file saved with index = ", index)

Data file saved with index =  88


In [3]:
NNN.print_ABC()
EEE.print_A()
EEE.print_AC()
EEE.print_index()

9.941898256564475
[22.97152386 23.01418715 23.02031977 23.09240758 23.03188657]
[110.16755827 110.37216423 110.40157522 110.74729623 110.45704766]
22.999999999999996


In [4]:
importlib.reload(NNN)

Opening data file in RRR, 88
in NNN, ABC = 68.08536056015319


<module 'NNN' from '/Users/ckishimoto/Desktop/git/new_QCD/NNN.py'>

In [5]:
NNN.print_ABC()
EEE.print_A()
EEE.print_AC()
EEE.print_index()

68.08536056015319
[88.2080625  88.05799631 88.02305143 87.95077459 87.99911948]
[827.46497297 826.05722738 825.72941531 825.05139841 825.50491373]
88.0
