In [1]:
import numpy as np
import NNN
import EEE
import importlib

Opening data file in RRR, 78
Opening data file in RRR, 78
in NNN, ABC = 56.10503329522573


In [2]:
index = np.random.randint(100)
np.savez("blah_data", i = index, A = index + 0.1*np.random.randn(5), B = -index + 0.1 * np.random.randn(8), C = np.sqrt(index))
print("Data file saved with index = ", index)

Data file saved with index =  22


In [3]:
NNN.print_ABC()
EEE.print_A()
EEE.print_AC()
EEE.print_index()

56.10503329522573
[78.19906743 77.97910631 77.97196089 77.98895634 78.15364313]
[690.63546354 688.69281953 688.62971288 688.77981258 690.23428694]
78.00000000000001


In [4]:
importlib.reload(NNN)

Opening data file in RRR, 22
in NNN, ABC = 8.314707840139851


<module 'NNN' from '/Users/ckishimoto/Desktop/git/new_QCD/NNN.py'>

In [5]:
NNN.print_ABC()
EEE.print_A()
EEE.print_AC()
EEE.print_index()

8.314707840139851
[22.07267129 22.01279833 21.83302138 22.04644272 22.11258533]
[103.53000528 103.24917621 102.40594755 103.40698237 103.71721873]
22.0
